### ISSUE TITLE
(Improvement) Chip Creation

### ISSUE THREAD

**Issue by okyloky9** [idakandrew/LogiStruct#1]
I saw this project under Sebastian Lague's simulator and I'm really happy. Really awesome project that is actively being worked on, exactly what I wanted out of Digital Logic Sim.
 
One thing I absolutely think needs to be added would be a layer of "obfuscation" with chip creation like DLS has. This will greatly save space, and make things neater and look nicer in the long-run.

**Comment by okyloky9** [comment]
Apologies I read that you're just going to do the blueprint system and drag select on there. Very unfortunate but I understand it's not easy. Good luck with the project! Thanks for bringing it!

**Comment by idakandrew** [comment]
@okyloky9

Yeah, I originally had planned to do an integrated circuit system, but the main issues that I ran into were:

1. No "objects" actually exist in LS, unlike DLS which stores everything in a list. Every "object" in LS essentially breaks down into a controller pixel which runs the actual logic, a direction pixel which tells the controller which direction it is facing, board pixels which serve to occupy the gate's physical area, and pin pixels which read and transmit signals. So rather than just running through a saved list like DLS can, I would have to simulate and entire sub-matrix for every chip.

2. Because of the "objectless" nature, placing a chip down involves running through and placing all the individual components in a hardcoded fashion. Therefore, dynamically sized chips wouldn't work in the current system. This could be solved by rewriting the placement system to read instructions from a file, which would dynamic sizes, but it would be a big effort.

In the end, it would be possible, but would require as much work as the entire rest of the project combined. That's why I ended up settling on blueprints instead (and even those will be tough to implement).
